# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/andre/Desktop/QTdesigner/tutorial.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(613, 616)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("*{\n"
"    border: none;\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: #fff;\n"
"}\n"
"#centralwidget{\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"#side_menu{\n"
"    background-color: #071e26;\n"
"    border-radius: 20px;\n"
"}\n"
"QPushButton{\n"
"    padding: 10px;\n"
"    background-color: #040f13;\n"
"    border-radius: 5px;\n"
"}\n"
"#main_body{\n"
"    background-color: #071e26;\n"
"    border-radius: 10px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(-1, 1, -1, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QFrame(self.centralwidget)
        self.header.setMinimumSize(QtCore.QSize(0, 50))
        self.header.setMaximumSize(QtCore.QSize(16777215, 50))
        self.header.setStyleSheet("")
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.header)
        self.frame.setMinimumSize(QtCore.QSize(150, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.menu = QtWidgets.QPushButton(self.frame)
        self.menu.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.menu.setFont(font)
        self.menu.setStyleSheet("background-color: rgb(0, 0, 0);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/menu (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu.setIcon(icon)
        self.menu.setIconSize(QtCore.QSize(20, 20))
        self.menu.setObjectName("menu")
        self.horizontalLayout_4.addWidget(self.menu)
        self.horizontalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignLeft)
        self.searchwidget = QtWidgets.QWidget(self.header)
        self.searchwidget.setMinimumSize(QtCore.QSize(0, 50))
        self.searchwidget.setObjectName("searchwidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.searchwidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.topLayout = QtWidgets.QHBoxLayout()
        self.topLayout.setObjectName("topLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topLayout.addItem(spacerItem)
        self.linkBar = QtWidgets.QLineEdit(self.searchwidget)
        self.linkBar.setMaximumSize(QtCore.QSize(400, 36))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.linkBar.setFont(font)
        self.linkBar.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border: 2px solid rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"padding-left: 10px;\n"
"font-size:20px;\n"
"padding-top:10px;\n"
"color: rgb(255, 255, 255);")
        self.linkBar.setText("")
        self.linkBar.setObjectName("linkBar")
        self.topLayout.addWidget(self.linkBar)
        self.pushButton_6 = QtWidgets.QPushButton(self.searchwidget)
        self.pushButton_6.setMaximumSize(QtCore.QSize(54, 40))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"height:40;\n"
"width: 50;\n"
"border-radius: 7px;\n"
"padding: 10px;\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #fa71cd, \n"
"                          stop: 1 #c471f5);\n"
"}")
        self.pushButton_6.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/colordownload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon1)
        self.pushButton_6.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_6.setObjectName("pushButton_6")
        self.topLayout.addWidget(self.pushButton_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topLayout.addItem(spacerItem1)
        self.topLayout.setStretch(1, 1)
        self.horizontalLayout_6.addLayout(self.topLayout)
        self.horizontalLayout_2.addWidget(self.searchwidget)
        self.frame_3 = QtWidgets.QFrame(self.header)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.header)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(-1, 7, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.side_menu = QtWidgets.QWidget(self.frame_2)
        self.side_menu.setMinimumSize(QtCore.QSize(160, 150))
        self.side_menu.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.side_menu.setObjectName("side_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.side_menu)
        self.verticalLayout_2.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.automaticButton = QtWidgets.QPushButton(self.side_menu)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.automaticButton.setFont(font)
        self.automaticButton.setObjectName("automaticButton")
        self.verticalLayout_2.addWidget(self.automaticButton)
        self.AutoWidget = QtWidgets.QWidget(self.side_menu)
        self.AutoWidget.setObjectName("AutoWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.AutoWidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.innerSettings = QtWidgets.QVBoxLayout()
        self.innerSettings.setContentsMargins(-1, -1, 4, -1)
        self.innerSettings.setSpacing(5)
        self.innerSettings.setObjectName("innerSettings")
        self.rectangleLabel = QtWidgets.QLabel(self.AutoWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.rectangleLabel.setFont(font)
        self.rectangleLabel.setObjectName("rectangleLabel")
        self.innerSettings.addWidget(self.rectangleLabel)
        self.combineOverLap = QtWidgets.QCheckBox(self.AutoWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.combineOverLap.setFont(font)
        self.combineOverLap.setStyleSheet("")
        self.combineOverLap.setChecked(True)
        self.combineOverLap.setObjectName("combineOverLap")
        self.innerSettings.addWidget(self.combineOverLap)
        self.combineNeighbors = QtWidgets.QCheckBox(self.AutoWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.combineNeighbors.setFont(font)
        self.combineNeighbors.setStyleSheet("")
        self.combineNeighbors.setObjectName("combineNeighbors")
        self.innerSettings.addWidget(self.combineNeighbors)
        self.rangeLabel = QtWidgets.QLabel(self.AutoWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.rangeLabel.setFont(font)
        self.rangeLabel.setStyleSheet("height:20;")
        self.rangeLabel.setObjectName("rangeLabel")
        self.innerSettings.addWidget(self.rangeLabel)
        self.rangeSlider = QtWidgets.QSlider(self.AutoWidget)
        self.rangeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.rangeSlider.setObjectName("rangeSlider")
        self.innerSettings.addWidget(self.rangeSlider)
        self.singlePtranslate = QtWidgets.QCheckBox(self.AutoWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(8)
        self.singlePtranslate.setFont(font)
        self.singlePtranslate.setIconSize(QtCore.QSize(12, 12))
        self.singlePtranslate.setObjectName("singlePtranslate")
        self.innerSettings.addWidget(self.singlePtranslate)
        self.verticalLayout_6.addLayout(self.innerSettings)
        self.verticalLayout_2.addWidget(self.AutoWidget)
        self.manualButton = QtWidgets.QPushButton(self.side_menu)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.manualButton.setFont(font)
        self.manualButton.setObjectName("manualButton")
        self.verticalLayout_2.addWidget(self.manualButton)
        self.ManualWidget = QtWidgets.QWidget(self.side_menu)
        self.ManualWidget.setObjectName("ManualWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.ManualWidget)
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.manualSet = QtWidgets.QVBoxLayout()
        self.manualSet.setSpacing(4)
        self.manualSet.setObjectName("manualSet")
        self.label_2 = QtWidgets.QLabel(self.ManualWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.manualSet.addWidget(self.label_2)
        self.Textcolor = QtWidgets.QComboBox(self.ManualWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.Textcolor.setFont(font)
        self.Textcolor.setStyleSheet("QComboBox{\n"
"border-color: rgb(85, 170, 255);\n"
"border-radius: 5px;\n"
"}\n"
"QComboBox::on{\n"
"border: 2px solid #c2dbfe;\n"
"}\n"
"QComboBox::drop-down{\n"
"border:0px;\n"
"}\n"
"QComboBox QListView\n"
"{\n"
"    border-style: none;\n"
"    background-color: white;\n"
"}\n"
"QComboBox::down-arrow\n"
"{\n"
"    \n"
"    \n"
"    \n"
"    image: url(:/newPrefix/down-chevron.png);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}")
        self.Textcolor.setObjectName("Textcolor")
        self.Textcolor.addItem("")
        self.Textcolor.addItem("")
        self.Textcolor.addItem("")
        self.Textcolor.addItem("")
        self.Textcolor.addItem("")
        self.manualSet.addWidget(self.Textcolor)
        self.label_3 = QtWidgets.QLabel(self.ManualWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.manualSet.addWidget(self.label_3)
        self.bGcolor = QtWidgets.QComboBox(self.ManualWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.bGcolor.setFont(font)
        self.bGcolor.setStyleSheet("QComboBox{\n"
"border-color: rgb(85, 170, 255);\n"
"}\n"
"QComboBox::on{\n"
"border: 2px solid #c2dbfe;\n"
"}\n"
"QComboBox::drop-down{\n"
"border:0px;\n"
"}\n"
"QComboBox QListView\n"
"{\n"
"    border-style: none;\n"
"    background-color: white;\n"
"}\n"
"QComboBox::down-arrow\n"
"{\n"
"    \n"
"    \n"
"    \n"
"    image: url(:/newPrefix/down-chevron.png);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}")
        self.bGcolor.setObjectName("bGcolor")
        self.bGcolor.addItem("")
        self.bGcolor.addItem("")
        self.bGcolor.addItem("")
        self.bGcolor.addItem("")
        self.bGcolor.addItem("")
        self.manualSet.addWidget(self.bGcolor)
        self.label_4 = QtWidgets.QLabel(self.ManualWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.manualSet.addWidget(self.label_4)
        self.fontsize = QtWidgets.QSlider(self.ManualWidget)
        self.fontsize.setToolTipDuration(1)
        self.fontsize.setMaximum(15)
        self.fontsize.setProperty("value", 6)
        self.fontsize.setSliderPosition(6)
        self.fontsize.setOrientation(QtCore.Qt.Horizontal)
        self.fontsize.setObjectName("fontsize")
        self.manualSet.addWidget(self.fontsize)
        self.removeRect = QtWidgets.QCheckBox(self.ManualWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.removeRect.setFont(font)
        self.removeRect.setObjectName("removeRect")
        self.manualSet.addWidget(self.removeRect)
        self.verticalLayout_7.addLayout(self.manualSet)
        self.verticalLayout_2.addWidget(self.ManualWidget)
        self.pushButton_5 = QtWidgets.QPushButton(self.side_menu)
        self.pushButton_5.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/gear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon2)
        self.pushButton_5.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.widget_2 = QtWidgets.QWidget(self.side_menu)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.sortButton = QtWidgets.QCheckBox(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.sortButton.setFont(font)
        self.sortButton.setObjectName("sortButton")
        self.verticalLayout_9.addWidget(self.sortButton)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_8.addWidget(self.label)
        self.translateOptions = QtWidgets.QComboBox(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.translateOptions.setFont(font)
        self.translateOptions.setStyleSheet("QComboBox{\n"
"border-color: rgb(85, 170, 255);\n"
"}\n"
"QComboBox::on{\n"
"border: 2px solid #c2dbfe;\n"
"}\n"
"QComboBox::drop-down{\n"
"border:0px;\n"
"}\n"
"QComboBox QListView\n"
"{\n"
"    border-style: none;\n"
"    background-color: white;\n"
"}\n"
"QComboBox::down-arrow\n"
"{\n"
"    \n"
"    \n"
"    \n"
"    image: url(:/newPrefix/down-chevron.png);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"")
        self.translateOptions.setObjectName("translateOptions")
        self.translateOptions.addItem("")
        self.translateOptions.addItem("")
        self.translateOptions.addItem("")
        self.verticalLayout_8.addWidget(self.translateOptions)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.advanced = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.advanced.setFont(font)
        self.advanced.setStyleSheet("QPushButton{\n"
"height:20;\n"
"width: 50;\n"
"padding: 10px;\n"
"background-color: #040f13;\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #fa71cd, \n"
"                          stop: 1 #c471f5);\n"
"}")
        self.advanced.setObjectName("advanced")
        self.verticalLayout_9.addWidget(self.advanced)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.side_menu)
        self.pushButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/twitter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon3)
        self.pushButton_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        spacerItem2 = QtWidgets.QSpacerItem(135, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout.addWidget(self.side_menu, 0, QtCore.Qt.AlignLeft)
        self.main_body = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_body.sizePolicy().hasHeightForWidth())
        self.main_body.setSizePolicy(sizePolicy)
        self.main_body.setMinimumSize(QtCore.QSize(200, 200))
        self.main_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.main_body)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.editRect = QtWidgets.QFrame(self.main_body)
        self.editRect.setMinimumSize(QtCore.QSize(80, 30))
        self.editRect.setMaximumSize(QtCore.QSize(150, 30))
        self.editRect.setToolTipDuration(0)
        self.editRect.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.editRect.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.editRect.setObjectName("editRect")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.editRect)
        self.horizontalLayout_7.setContentsMargins(8, -1, -1, -1)
        self.horizontalLayout_7.setSpacing(5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.undoButton = QtWidgets.QPushButton(self.editRect)
        self.undoButton.setMinimumSize(QtCore.QSize(20, 20))
        self.undoButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.undoButton.setStyleSheet("QPushButton{\n"
"border:none;\n"
"width:20px;\n"
"height:20px;\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:hover:!pressed{\n"
"border:1px solid rgb(170, 0, 255);\n"
"}")
        self.undoButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/forward1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undoButton.setIcon(icon4)
        self.undoButton.setIconSize(QtCore.QSize(20, 20))
        self.undoButton.setObjectName("undoButton")
        self.horizontalLayout_7.addWidget(self.undoButton)
        self.eraseButton = QtWidgets.QPushButton(self.editRect)
        self.eraseButton.setMinimumSize(QtCore.QSize(20, 20))
        self.eraseButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.eraseButton.setStyleSheet("QPushButton{\n"
"border:none;\n"
"width:20px;\n"
"height:20px;\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:hover:!pressed{\n"
"border:1px solid rgb(170, 0, 255);\n"
"}\n"
"\n"
"")
        self.eraseButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/eraser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eraseButton.setIcon(icon5)
        self.eraseButton.setIconSize(QtCore.QSize(20, 20))
        self.eraseButton.setObjectName("eraseButton")
        self.horizontalLayout_7.addWidget(self.eraseButton)
        self.redoButton = QtWidgets.QPushButton(self.editRect)
        self.redoButton.setMinimumSize(QtCore.QSize(20, 20))
        self.redoButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.redoButton.setStyleSheet("QPushButton{\n"
"border:none;\n"
"width:20px;\n"
"height:20px;\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:hover:!pressed{\n"
"border:1px solid rgb(170, 0, 255);\n"
"}")
        self.redoButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.redoButton.setIcon(icon6)
        self.redoButton.setIconSize(QtCore.QSize(20, 20))
        self.redoButton.setObjectName("redoButton")
        self.horizontalLayout_7.addWidget(self.redoButton)
        self.verticalLayout_4.addWidget(self.editRect, 0, QtCore.Qt.AlignHCenter)
        self.imageDisplay = QtWidgets.QHBoxLayout()
        self.imageDisplay.setObjectName("imageDisplay")
        self.leftArrow = QtWidgets.QPushButton(self.main_body)
        self.leftArrow.setMaximumSize(QtCore.QSize(70, 90))
        self.leftArrow.setStyleSheet("QPushButton{\n"
"height:90;\n"
"width: 70;\n"
"border-radius: 25px;\n"
"padding: 10px;\n"
"background-color: #040f13;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #c471f5, \n"
"                          stop: 1 #fa71cd );\n"
"}")
        self.leftArrow.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/play1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leftArrow.setIcon(icon7)
        self.leftArrow.setIconSize(QtCore.QSize(50, 50))
        self.leftArrow.setObjectName("leftArrow")
        self.imageDisplay.addWidget(self.leftArrow)
        self.imageWidget = QtWidgets.QWidget(self.main_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageWidget.sizePolicy().hasHeightForWidth())
        self.imageWidget.setSizePolicy(sizePolicy)
        self.imageWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.imageWidget.setMaximumSize(QtCore.QSize(400, 300))
        self.imageWidget.setStyleSheet("background-color: #040f13;\n"
"border-radius: 10px")
        self.imageWidget.setObjectName("imageWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.imageWidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.imageDisplay.addWidget(self.imageWidget)
        self.rightArrow = QtWidgets.QPushButton(self.main_body)
        self.rightArrow.setMaximumSize(QtCore.QSize(70, 90))
        self.rightArrow.setStyleSheet("QPushButton{\n"
"height:90;\n"
"width: 70;\n"
"border-radius: 25px;\n"
"padding: 10px;\n"
"background-color: #040f13;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #c471f5, \n"
"                          stop: 1 #fa71cd );\n"
"}")
        self.rightArrow.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rightArrow.setIcon(icon8)
        self.rightArrow.setIconSize(QtCore.QSize(50, 50))
        self.rightArrow.setObjectName("rightArrow")
        self.imageDisplay.addWidget(self.rightArrow)
        self.imageDisplay.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.imageDisplay)
        self.bar = QtWidgets.QProgressBar(self.main_body)
        self.bar.setMinimumSize(QtCore.QSize(200, 30))
        self.bar.setMaximumSize(QtCore.QSize(200, 30))
        self.bar.setProperty("value", 24)
        self.bar.setObjectName("bar")
        self.verticalLayout_4.addWidget(self.bar, 0, QtCore.Qt.AlignHCenter)
        self.actionButtons = QtWidgets.QHBoxLayout()
        self.actionButtons.setSpacing(10)
        self.actionButtons.setObjectName("actionButtons")
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.actionButtons.addItem(spacerItem3)
        self.upload = QtWidgets.QPushButton(self.main_body)
        self.upload.setMaximumSize(QtCore.QSize(130, 45))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.upload.setFont(font)
        self.upload.setStyleSheet("QPushButton{\n"
"height:20;\n"
"width: 30;\n"
"border-radius: 7px;\n"
"padding: 10px;\n"
"background-color: #040f13;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #c471f5, \n"
"                          stop: 1 #fa71cd );\n"
"}")
        self.upload.setObjectName("upload")
        self.actionButtons.addWidget(self.upload)
        self.translate = QtWidgets.QPushButton(self.main_body)
        self.translate.setMaximumSize(QtCore.QSize(130, 45))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.translate.setFont(font)
        self.translate.setStyleSheet("QPushButton{\n"
"height:20;\n"
"width: 30;\n"
"border-radius: 7px;\n"
"padding: 5px;\n"
"background-color: #040f13;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #c471f5, \n"
"                          stop: 1 #fa71cd );\n"
"}")
        self.translate.setObjectName("translate")
        self.actionButtons.addWidget(self.translate)
        self.saveButton = QtWidgets.QPushButton(self.main_body)
        self.saveButton.setMaximumSize(QtCore.QSize(130, 45))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.saveButton.setFont(font)
        self.saveButton.setStyleSheet("QPushButton{\n"
"height:20;\n"
"width: 30;\n"
"border-radius: 7px;\n"
"padding: 10px;\n"
"background-color: #040f13;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #c471f5, \n"
"                          stop: 1 #fa71cd );\n"
"}")
        self.saveButton.setObjectName("saveButton")
        self.actionButtons.addWidget(self.saveButton)
        self.clearButton = QtWidgets.QPushButton(self.main_body)
        self.clearButton.setMaximumSize(QtCore.QSize(130, 45))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.clearButton.setFont(font)
        self.clearButton.setStyleSheet("QPushButton{\n"
"height:20;\n"
"width: 30;\n"
"border-radius: 7px;\n"
"padding: 10px;\n"
"background-color: #040f13;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #c471f5, \n"
"                          stop: 1 #fa71cd );\n"
"}")
        self.clearButton.setObjectName("clearButton")
        self.actionButtons.addWidget(self.clearButton)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.actionButtons.addItem(spacerItem4)
        self.actionButtons.setStretch(1, 1)
        self.actionButtons.setStretch(2, 1)
        self.actionButtons.setStretch(3, 1)
        self.actionButtons.setStretch(4, 1)
        self.verticalLayout_4.addLayout(self.actionButtons)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addWidget(self.main_body)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setText(_translate("MainWindow", "Menu"))
        self.linkBar.setPlaceholderText(_translate("MainWindow", "Download from Twitter"))
        self.automaticButton.setText(_translate("MainWindow", "Automatic"))
        self.rectangleLabel.setText(_translate("MainWindow", "Rectangles"))
        self.combineOverLap.setText(_translate("MainWindow", "CombineOverlap"))
        self.combineNeighbors.setText(_translate("MainWindow", "CombineNeighbors"))
        self.rangeLabel.setText(_translate("MainWindow", "Range"))
        self.singlePtranslate.setText(_translate("MainWindow", "Retranslate current page"))
        self.manualButton.setText(_translate("MainWindow", "Manual"))
        self.label_2.setText(_translate("MainWindow", "Colors:"))
        self.Textcolor.setItemText(0, _translate("MainWindow", "Red"))
        self.Textcolor.setItemText(1, _translate("MainWindow", "Blue"))
        self.Textcolor.setItemText(2, _translate("MainWindow", "Green"))
        self.Textcolor.setItemText(3, _translate("MainWindow", "Black"))
        self.Textcolor.setItemText(4, _translate("MainWindow", "White"))
        self.label_3.setText(_translate("MainWindow", "Background Color:"))
        self.bGcolor.setItemText(0, _translate("MainWindow", "White"))
        self.bGcolor.setItemText(1, _translate("MainWindow", "Red"))
        self.bGcolor.setItemText(2, _translate("MainWindow", "Blue"))
        self.bGcolor.setItemText(3, _translate("MainWindow", "Green"))
        self.bGcolor.setItemText(4, _translate("MainWindow", "Black"))
        self.label_4.setText(_translate("MainWindow", "Font Size: 6"))
        self.removeRect.setText(_translate("MainWindow", "Remove rectangles"))
        self.sortButton.setText(_translate("MainWindow", "Sort pages by file name"))
        self.label.setText(_translate("MainWindow", "Translators:"))
        self.translateOptions.setItemText(0, _translate("MainWindow", "Bing"))
        self.translateOptions.setItemText(1, _translate("MainWindow", "Google"))
        self.translateOptions.setItemText(2, _translate("MainWindow", "DeepL"))
        self.advanced.setText(_translate("MainWindow", "Advanced Option"))
        self.upload.setText(_translate("MainWindow", "Upload"))
        self.translate.setText(_translate("MainWindow", "Translate"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
import darkmode_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
