# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/andre/Desktop/QTdesigner/MainApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(540, 394)
        MainWindow.setMinimumSize(QtCore.QSize(100, 100))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #0f121c, \n"
"                          stop: 1 #0b0d14);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(20, -1, 10, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setHorizontalSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setStyleSheet("background-color: rgb(39, 39, 39);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.automaticButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(7)
        self.automaticButton.setFont(font)
        self.automaticButton.setStyleSheet("QPushButton{\n"
"height:40;\n"
"width: 50;\n"
"border-radius: 15px;\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #fa71cd, \n"
"                          stop: 1 #c471f5);\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #fa71cd, \n"
"                          stop: 1 #c471f5);\n"
"}")
        self.automaticButton.setObjectName("automaticButton")
        self.verticalLayout.addWidget(self.automaticButton)
        self.manualButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.manualButton.setFont(font)
        self.manualButton.setStyleSheet("QPushButton{\n"
"height:40;\n"
"width: 50;\n"
"border-radius: 15px;\n"
"background-color: rgb(82, 82, 82);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #fa71cd, \n"
"                          stop: 1 #c471f5);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.manualButton.setObjectName("manualButton")
        self.verticalLayout.addWidget(self.manualButton)
        self.setButton = QtWidgets.QPushButton(self.widget)
        self.setButton.setMaximumSize(QtCore.QSize(11111111, 16777215))
        self.setButton.setStyleSheet("QPushButton{\n"
"height:50;\n"
"width: 50;\n"
"border-radius: 15px;\n"
"background-color: rgb(82, 82, 82);\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #c471f5, \n"
"                          stop: 1 #fa71cd );\n"
"}")
        self.setButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/andre/Desktop/QTdesigner\\../Lab01/MangaTranslation/Icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setButton.setIcon(icon)
        self.setButton.setIconSize(QtCore.QSize(30, 30))
        self.setButton.setObjectName("setButton")
        self.verticalLayout.addWidget(self.setButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"height:50;\n"
"width: 50;\n"
"border-radius: 15px;\n"
"background-color: rgb(83, 83, 83);\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #c471f5, \n"
"                          stop: 1 #fa71cd );\n"
"}")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/twitter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.widget)
        self.settings = QtWidgets.QWidget(self.centralwidget)
        self.settings.setEnabled(True)
        self.settings.setMaximumSize(QtCore.QSize(144, 16777215))
        self.settings.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;")
        self.settings.setObjectName("settings")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.settings)
        self.verticalLayout_2.setContentsMargins(-1, -1, 6, -1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.AutoWidget = QtWidgets.QWidget(self.settings)
        self.AutoWidget.setObjectName("AutoWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.AutoWidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.AutoWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.innerSettings = QtWidgets.QVBoxLayout()
        self.innerSettings.setContentsMargins(-1, -1, 4, -1)
        self.innerSettings.setSpacing(5)
        self.innerSettings.setObjectName("innerSettings")
        self.rectangleLabel = QtWidgets.QLabel(self.AutoWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.rectangleLabel.setFont(font)
        self.rectangleLabel.setObjectName("rectangleLabel")
        self.innerSettings.addWidget(self.rectangleLabel)
        self.combineOverLap = QtWidgets.QCheckBox(self.AutoWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.combineOverLap.setFont(font)
        self.combineOverLap.setStyleSheet("background-color:white;")
        self.combineOverLap.setChecked(True)
        self.combineOverLap.setObjectName("combineOverLap")
        self.innerSettings.addWidget(self.combineOverLap)
        self.combineNeighbors = QtWidgets.QCheckBox(self.AutoWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.combineNeighbors.setFont(font)
        self.combineNeighbors.setStyleSheet("background-color:white;")
        self.combineNeighbors.setObjectName("combineNeighbors")
        self.innerSettings.addWidget(self.combineNeighbors)
        self.rangeLabel = QtWidgets.QLabel(self.AutoWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.rangeLabel.setFont(font)
        self.rangeLabel.setStyleSheet("background-color:white;\n"
"height:20;")
        self.rangeLabel.setObjectName("rangeLabel")
        self.innerSettings.addWidget(self.rangeLabel)
        self.rangeSlider = QtWidgets.QSlider(self.AutoWidget)
        self.rangeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.rangeSlider.setObjectName("rangeSlider")
        self.innerSettings.addWidget(self.rangeSlider)
        self.singlePtranslate = QtWidgets.QCheckBox(self.AutoWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(8)
        self.singlePtranslate.setFont(font)
        self.singlePtranslate.setIconSize(QtCore.QSize(12, 12))
        self.singlePtranslate.setObjectName("singlePtranslate")
        self.innerSettings.addWidget(self.singlePtranslate)
        self.verticalLayout_6.addLayout(self.innerSettings)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.AutoWidget)
        self.ManualWidget = QtWidgets.QWidget(self.settings)
        self.ManualWidget.setObjectName("ManualWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.ManualWidget)
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.ManualWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter)
        self.manualSet = QtWidgets.QVBoxLayout()
        self.manualSet.setSpacing(4)
        self.manualSet.setObjectName("manualSet")
        self.label_2 = QtWidgets.QLabel(self.ManualWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.manualSet.addWidget(self.label_2)
        self.Textcolor = QtWidgets.QComboBox(self.ManualWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.Textcolor.setFont(font)
        self.Textcolor.setStyleSheet("QComboBox{\n"
"background-color: white;\n"
"border-color: rgb(85, 170, 255);\n"
"}\n"
"QComboBox::on{\n"
"border: 2px solid #c2dbfe;\n"
"}\n"
"QComboBox::drop-down{\n"
"border:0px;\n"
"}\n"
"QComboBox QListView\n"
"{\n"
"    border-style: none;\n"
"    background-color: white;\n"
"}\n"
"QComboBox::down-arrow\n"
"{\n"
"    \n"
"    \n"
"    image: url(:/newPrefix/downArrow.png);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}")
        self.Textcolor.setObjectName("Textcolor")
        self.Textcolor.addItem("")
        self.Textcolor.addItem("")
        self.Textcolor.addItem("")
        self.Textcolor.addItem("")
        self.Textcolor.addItem("")
        self.manualSet.addWidget(self.Textcolor)
        self.label_3 = QtWidgets.QLabel(self.ManualWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.manualSet.addWidget(self.label_3)
        self.bGcolor = QtWidgets.QComboBox(self.ManualWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.bGcolor.setFont(font)
        self.bGcolor.setStyleSheet("QComboBox{\n"
"background-color: white;\n"
"border-color: rgb(85, 170, 255);\n"
"}\n"
"QComboBox::on{\n"
"border: 2px solid #c2dbfe;\n"
"}\n"
"QComboBox::drop-down{\n"
"border:0px;\n"
"}\n"
"QComboBox QListView\n"
"{\n"
"    border-style: none;\n"
"    background-color: white;\n"
"}\n"
"QComboBox::down-arrow\n"
"{\n"
"    \n"
"    \n"
"    image: url(:/newPrefix/downArrow.png);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}")
        self.bGcolor.setObjectName("bGcolor")
        self.bGcolor.addItem("")
        self.bGcolor.addItem("")
        self.bGcolor.addItem("")
        self.bGcolor.addItem("")
        self.bGcolor.addItem("")
        self.manualSet.addWidget(self.bGcolor)
        self.label_4 = QtWidgets.QLabel(self.ManualWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.manualSet.addWidget(self.label_4)
        self.fontsize = QtWidgets.QSlider(self.ManualWidget)
        self.fontsize.setToolTipDuration(1)
        self.fontsize.setMaximum(15)
        self.fontsize.setProperty("value", 6)
        self.fontsize.setSliderPosition(6)
        self.fontsize.setOrientation(QtCore.Qt.Horizontal)
        self.fontsize.setObjectName("fontsize")
        self.manualSet.addWidget(self.fontsize)
        self.removeRect = QtWidgets.QCheckBox(self.ManualWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.removeRect.setFont(font)
        self.removeRect.setObjectName("removeRect")
        self.manualSet.addWidget(self.removeRect)
        self.verticalLayout_7.addLayout(self.manualSet)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.ManualWidget)
        self.widget_2 = QtWidgets.QWidget(self.settings)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_10.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.sortButton = QtWidgets.QCheckBox(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.sortButton.setFont(font)
        self.sortButton.setObjectName("sortButton")
        self.verticalLayout_9.addWidget(self.sortButton)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_8.addWidget(self.label)
        self.translateOptions = QtWidgets.QComboBox(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.translateOptions.setFont(font)
        self.translateOptions.setStyleSheet("QComboBox{\n"
"background-color: white;\n"
"border-color: rgb(85, 170, 255);\n"
"}\n"
"QComboBox::on{\n"
"border: 2px solid #c2dbfe;\n"
"}\n"
"QComboBox::drop-down{\n"
"border:0px;\n"
"}\n"
"QComboBox QListView\n"
"{\n"
"    border-style: none;\n"
"    background-color: white;\n"
"}\n"
"QComboBox::down-arrow\n"
"{\n"
"    \n"
"    \n"
"    image: url(:/newPrefix/downArrow.png);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"")
        self.translateOptions.setObjectName("translateOptions")
        self.translateOptions.addItem("")
        self.translateOptions.addItem("")
        self.translateOptions.addItem("")
        self.verticalLayout_8.addWidget(self.translateOptions)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.advanced = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.advanced.setFont(font)
        self.advanced.setStyleSheet("QPushButton{\n"
"height:20;\n"
"width: 50;\n"
"border-radius: 5px;\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #dfe9f3, \n"
"                          stop: 1 white );\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #fa71cd, \n"
"                          stop: 1 #c471f5);\n"
"}")
        self.advanced.setObjectName("advanced")
        self.verticalLayout_9.addWidget(self.advanced)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.widget_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.settings)
        self.verticalLayout_4.addLayout(self.formLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        spacerItem6 = QtWidgets.QSpacerItem(13, 356, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.searchwidget = QtWidgets.QWidget(self.centralwidget)
        self.searchwidget.setObjectName("searchwidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.searchwidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.topLayout = QtWidgets.QHBoxLayout()
        self.topLayout.setObjectName("topLayout")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topLayout.addItem(spacerItem8)
        self.linkBar = QtWidgets.QLineEdit(self.searchwidget)
        self.linkBar.setMaximumSize(QtCore.QSize(400, 36))
        font = QtGui.QFont()
        self.linkBar.setFont(font)
        self.linkBar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"padding-left: 10px;\n"
"font-size:20px;\n"
"padding-top:10px;\n"
"color: rgb(0, 0, 0);")
        self.linkBar.setText("")
        self.linkBar.setObjectName("linkBar")
        self.topLayout.addWidget(self.linkBar)
        self.pushButton = QtWidgets.QPushButton(self.searchwidget)
        self.pushButton.setMaximumSize(QtCore.QSize(54, 40))
        self.pushButton.setStyleSheet("QPushButton{\n"
"height:40;\n"
"width: 50;\n"
"border-radius: 15px;\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #dfe9f3, \n"
"                          stop: 1 white );\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #fa71cd, \n"
"                          stop: 1 #c471f5);\n"
"}")
        self.pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/andre/Desktop/QTdesigner\\../Lab01/MangaTranslation/Icons/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        self.topLayout.addWidget(self.pushButton)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topLayout.addItem(spacerItem9)
        self.topLayout.setStretch(1, 1)
        self.horizontalLayout_6.addLayout(self.topLayout)
        self.verticalLayout_3.addWidget(self.searchwidget)
        self.editRect = QtWidgets.QWidget(self.centralwidget)
        self.editRect.setMinimumSize(QtCore.QSize(150, 30))
        self.editRect.setMaximumSize(QtCore.QSize(150, 30))
        self.editRect.setToolTipDuration(0)
        self.editRect.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.editRect.setObjectName("editRect")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.editRect)
        self.horizontalLayout_3.setContentsMargins(8, -1, -1, -1)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.undoButton = QtWidgets.QPushButton(self.editRect)
        self.undoButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.undoButton.setStyleSheet("QPushButton{\n"
"border:none;\n"
"width:20px;\n"
"height:20px;\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:hover:!pressed{\n"
"border:1px solid rgb(170, 0, 255);\n"
"}")
        self.undoButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/forward1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undoButton.setIcon(icon3)
        self.undoButton.setObjectName("undoButton")
        self.horizontalLayout_3.addWidget(self.undoButton)
        self.eraseButton = QtWidgets.QPushButton(self.editRect)
        self.eraseButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.eraseButton.setStyleSheet("QPushButton{\n"
"border:none;\n"
"width:20px;\n"
"height:20px;\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:hover:!pressed{\n"
"border:1px solid rgb(170, 0, 255);\n"
"}\n"
"\n"
"")
        self.eraseButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/eraser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eraseButton.setIcon(icon4)
        self.eraseButton.setIconSize(QtCore.QSize(20, 20))
        self.eraseButton.setObjectName("eraseButton")
        self.horizontalLayout_3.addWidget(self.eraseButton)
        self.redoButton = QtWidgets.QPushButton(self.editRect)
        self.redoButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.redoButton.setStyleSheet("QPushButton{\n"
"border:none;\n"
"width:20px;\n"
"height:20px;\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:hover:!pressed{\n"
"border:1px solid rgb(170, 0, 255);\n"
"}")
        self.redoButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.redoButton.setIcon(icon5)
        self.redoButton.setIconSize(QtCore.QSize(20, 20))
        self.redoButton.setObjectName("redoButton")
        self.horizontalLayout_3.addWidget(self.redoButton)
        self.verticalLayout_3.addWidget(self.editRect, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.imageDisplay = QtWidgets.QHBoxLayout()
        self.imageDisplay.setObjectName("imageDisplay")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.imageDisplay.addItem(spacerItem10)
        self.leftArrow = QtWidgets.QPushButton(self.centralwidget)
        self.leftArrow.setMaximumSize(QtCore.QSize(70, 90))
        self.leftArrow.setStyleSheet("QPushButton{\n"
"height:90;\n"
"width: 70;\n"
"border-radius: 25px;\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #dfe9f3, \n"
"                          stop: 1 white );\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #c471f5, \n"
"                          stop: 1 #fa71cd );\n"
"}")
        self.leftArrow.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("C:/Users/andre/Desktop/QTdesigner\\../Lab01/MangaTranslation/Icons/arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leftArrow.setIcon(icon6)
        self.leftArrow.setIconSize(QtCore.QSize(20, 20))
        self.leftArrow.setObjectName("leftArrow")
        self.imageDisplay.addWidget(self.leftArrow)
        self.imageWidget = QtWidgets.QWidget(self.centralwidget)
        self.imageWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.imageWidget.setMaximumSize(QtCore.QSize(400, 300))
        self.imageWidget.setStyleSheet("background:white;\n"
"border-radius: 10px")
        self.imageWidget.setObjectName("imageWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.imageWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.imageDisplay.addWidget(self.imageWidget)
        self.rightArrow = QtWidgets.QPushButton(self.centralwidget)
        self.rightArrow.setMaximumSize(QtCore.QSize(70, 90))
        self.rightArrow.setStyleSheet("QPushButton{\n"
"height:90;\n"
"width: 70;\n"
"border-radius: 25px;\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #dfe9f3, \n"
"                          stop: 1 white );\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #c471f5, \n"
"                          stop: 1 #fa71cd );\n"
"}")
        self.rightArrow.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("C:/Users/andre/Desktop/QTdesigner\\../Lab01/MangaTranslation/Icons/arrow1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rightArrow.setIcon(icon7)
        self.rightArrow.setIconSize(QtCore.QSize(20, 20))
        self.rightArrow.setObjectName("rightArrow")
        self.imageDisplay.addWidget(self.rightArrow)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.imageDisplay.addItem(spacerItem11)
        self.imageDisplay.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.imageDisplay)
        self.bar = QtWidgets.QProgressBar(self.centralwidget)
        self.bar.setMinimumSize(QtCore.QSize(200, 30))
        self.bar.setMaximumSize(QtCore.QSize(200, 30))
        self.bar.setProperty("value", 24)
        self.bar.setObjectName("bar")
        self.verticalLayout_3.addWidget(self.bar, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.actionButtons = QtWidgets.QHBoxLayout()
        self.actionButtons.setSpacing(10)
        self.actionButtons.setObjectName("actionButtons")
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.actionButtons.addItem(spacerItem12)
        self.upload = QtWidgets.QPushButton(self.centralwidget)
        self.upload.setMaximumSize(QtCore.QSize(130, 45))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.upload.setFont(font)
        self.upload.setStyleSheet("QPushButton{\n"
"height:20;\n"
"width: 30;\n"
"border-radius: 7px;\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #dfe9f3, \n"
"                          stop: 1 white );\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #c471f5, \n"
"                          stop: 1 #fa71cd );\n"
"}")
        self.upload.setObjectName("upload")
        self.actionButtons.addWidget(self.upload)
        self.translate = QtWidgets.QPushButton(self.centralwidget)
        self.translate.setMaximumSize(QtCore.QSize(130, 45))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.translate.setFont(font)
        self.translate.setStyleSheet("QPushButton{\n"
"height:20;\n"
"width: 30;\n"
"border-radius: 7px;\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #dfe9f3, \n"
"                          stop: 1 white );\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #c471f5, \n"
"                          stop: 1 #fa71cd );\n"
"}")
        self.translate.setObjectName("translate")
        self.actionButtons.addWidget(self.translate)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setMaximumSize(QtCore.QSize(130, 45))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.saveButton.setFont(font)
        self.saveButton.setStyleSheet("QPushButton{\n"
"height:20;\n"
"width: 30;\n"
"border-radius: 7px;\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #dfe9f3, \n"
"                          stop: 1 white );\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #c471f5, \n"
"                          stop: 1 #fa71cd );\n"
"}")
        self.saveButton.setObjectName("saveButton")
        self.actionButtons.addWidget(self.saveButton)
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setMaximumSize(QtCore.QSize(130, 45))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.clearButton.setFont(font)
        self.clearButton.setStyleSheet("QPushButton{\n"
"height:20;\n"
"width: 30;\n"
"border-radius: 7px;\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #dfe9f3, \n"
"                          stop: 1 white );\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"background-color: QLinearGradient( x1: 0, y1: 0,\n"
"                             x2: 1, y2: 0, \n"
"                          stop: 0 #c471f5, \n"
"                          stop: 1 #fa71cd );\n"
"}")
        self.clearButton.setObjectName("clearButton")
        self.actionButtons.addWidget(self.clearButton)
        spacerItem13 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.actionButtons.addItem(spacerItem13)
        self.actionButtons.setStretch(1, 1)
        self.actionButtons.setStretch(2, 1)
        self.actionButtons.setStretch(3, 1)
        self.actionButtons.setStretch(4, 1)
        self.verticalLayout_3.addLayout(self.actionButtons)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem14)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem15 = QtWidgets.QSpacerItem(13, 356, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem15)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.automaticButton.setText(_translate("MainWindow", "Automatic"))
        self.manualButton.setText(_translate("MainWindow", "Manual"))
        self.label_5.setText(_translate("MainWindow", "Automatic Settings"))
        self.rectangleLabel.setText(_translate("MainWindow", "Rectangles"))
        self.combineOverLap.setText(_translate("MainWindow", "CombineOverlap"))
        self.combineNeighbors.setText(_translate("MainWindow", "CombineNeighbors"))
        self.rangeLabel.setText(_translate("MainWindow", "Range"))
        self.singlePtranslate.setText(_translate("MainWindow", "Retranslate current page"))
        self.label_6.setText(_translate("MainWindow", "Manual Settings"))
        self.label_2.setText(_translate("MainWindow", "Colors:"))
        self.Textcolor.setItemText(0, _translate("MainWindow", "Red"))
        self.Textcolor.setItemText(1, _translate("MainWindow", "Blue"))
        self.Textcolor.setItemText(2, _translate("MainWindow", "Green"))
        self.Textcolor.setItemText(3, _translate("MainWindow", "Black"))
        self.Textcolor.setItemText(4, _translate("MainWindow", "White"))
        self.label_3.setText(_translate("MainWindow", "Background Color:"))
        self.bGcolor.setItemText(0, _translate("MainWindow", "White"))
        self.bGcolor.setItemText(1, _translate("MainWindow", "Red"))
        self.bGcolor.setItemText(2, _translate("MainWindow", "Blue"))
        self.bGcolor.setItemText(3, _translate("MainWindow", "Green"))
        self.bGcolor.setItemText(4, _translate("MainWindow", "Black"))
        self.label_4.setText(_translate("MainWindow", "Font Size: 6"))
        self.removeRect.setText(_translate("MainWindow", "Remove rectangles"))
        self.label_7.setText(_translate("MainWindow", "Settings"))
        self.sortButton.setText(_translate("MainWindow", "Sort pages by file name"))
        self.label.setText(_translate("MainWindow", "Translators:"))
        self.translateOptions.setItemText(0, _translate("MainWindow", "Bing"))
        self.translateOptions.setItemText(1, _translate("MainWindow", "Google"))
        self.translateOptions.setItemText(2, _translate("MainWindow", "DeepL"))
        self.advanced.setText(_translate("MainWindow", "Advanced Option"))
        self.linkBar.setPlaceholderText(_translate("MainWindow", "Download from Twitter"))
        self.upload.setText(_translate("MainWindow", "Upload"))
        self.translate.setText(_translate("MainWindow", "Translate"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
import stuff_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
